site_name: Proyecto Electromagnetismo
nav:
  - Inicio: index.md
  - Métodos en Python:
      - Relajación Jacobi: Codigo_python/Relajacion_Jacobi.md
      - Jacobi Modificado: Codigo_python/jacobi_modificado.md
      - Gauss Seidel: Codigo_python/Gauss_Seidel.md
  - Código en C++:
      - Gauss Seidel: Codigo_cpp/Gauss_Seidel.md
      - Gauss Seidel en memoria compartida: Codigo_cpp/Gauss_Seidel_Memloc.md
      - Gauss Seidel en memoria distribuida: Codigo_cpp/Gauss_Seidel_Dist.md
theme:
  name: material
  palette:
    primary: deep-purple
    accent: light-blue
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js




